### PR TITLE
refactor: Use async/await

### PR DESCRIPTION
**Pull request by FoPi**
- Make async/await the szamlazz.hu communication
- Make async/await the XMLUtils conversion
- Major version change
- Apply some refactor

closes issue #9

### CODE REVIEW

**Comment by FoPi** [comment]
TODO: use cookiejar suggested package `axios-cookiejar-support`

**Comment by FoPi** [comment]
`axios-cookiejar-support` Cookie jar added

**Comment by mondalaci** [comment]
Your PR does look impressive, but I'm a bit stressed regarding such a sweeping change. I'd have preferred a step-by-step approach which is easier to review. What's the rationale for replacing request with axios?

**Comment by FoPi** [comment]
Sorry for the huge commit. I have just moved the production code that we use in our software to here. I've just needed the async/await asap.
I can re-implement it in smaller steps, but I will need time for this.
The switch from request to axios was because I am more familiar with it.
I can try to rewrite it and use request for communication.

**Pull request merged**
